# /docker-compose.yml
services:

  chainlitdb:
    image: postgres:16
    volumes:
      - ./.data/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-root}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-root}
      - POSTGRES_DB=${POSTGRES_DB:-postgres}
    ports:
      - ${POSTGRES_PORT:-5432}:5432


  backend:
    build: ./backend
    image: chainlitb
    ports:
      - 8000:8000    
    environment:
      - DATABASE_URL=postgresql://root:root@chainlitdb:5432/postgres
      - CHAINLIT_AUTH_SECRET="HZohuMm7$$RUfY?q5T^5b6Lb7rlEskk9irCA>aWPX_9:a@i_RaOL.c_2_H_bo-w?v"

    command: "./backend.sh"
    labels:
      - traefik.http.routers.backend.rule=PathPrefix(`/api`) || PathPrefix(`/docs`) || PathPrefix(`/redoc`) || PathPrefix(`/open`)
      - traefik.http.services.backend.loadbalancer.server.port=80


  # frontend:
  #   build: ./frontend
  #   working_dir: /var/www/html/app/
  #   ports:
  #     - '5173:5173'
  #   volumes:
  #     - ~/.ssh:/root/.ssh:ro
  #     - ./frontend:/var/www/html/app/
  #   # command: "yarn dev --host --port 5544"
  #   # command: "yarn add react-virtualized"
  #   entrypoint: /bin/bash
  #   tty: true

